authors:
    maroph:
        name: Manfred Rosenboom
        description: Author
        # avatar: https://raw.githubusercontent.com/maroph/nosense_mkdocs_material/refs/heads/main/docs/assets/great_wave_off_kanagawa_200x200.jpg
        avatar: https://maroph.github.io/nosense_mkdocs_material/assets/great_wave_off_kanagawa_200x200.jpg
        url: https://github.com/maroph
